### ISSUE TITLE
Published versions need to be available

### ISSUE THREAD

**Issue by daviddias** [haadcode/ipfs-daemon#7]
Getting a `npm ERR! git rev-list -n1 deb5fd6: fatal: ambiguous argument 'deb5fd6': unknown revision or path not in the working tree.` while installing orbit and it all resumes because this module is lock on a git hash for installing a dependency.

What blocks me from moving forward smoothly is that the beta8 is nowhere, npm only has beta7 published and there are no tags in this repo, the last commit being beta 4

![image](https://cloud.githubusercontent.com/assets/1211152/21123913/98388fca-c090-11e6-9efe-b34cfa827036.png)

![image](https://cloud.githubusercontent.com/assets/1211152/21123933/ac6ecbb2-c090-11e6-8f06-cd7c244ae00f.png)

**Comment by haadcode** [comment]
This is fixed now. Squashed a little aggressively earlier losing the beta.x between 4 and 10.

**Comment by daviddias** [comment]
Would be great to also have tag released with each npm publish (aegir does this for free), this way we won't loose versions again.
